# Generated by Django 5.2.6 on 2025-09-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0038_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="foodcartapp.order",
                verbose_name="Продукты",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Количество"),
            preserve_default=False,
        ),
    ]
