# Generated by Django 5.2.6 on 2025-09-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="foodcartapp.order",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_products",
                        to="foodcartapp.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
        ),
    ]
