# Generated by Django 5.2.6 on 2025-09-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0040_remove_product_order_remove_product_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restaurants",
                to="foodcartapp.restaurant",
                verbose_name="Ресторан",
            ),
            preserve_default=False,
        ),
    ]
