# Generated by Django 5.2.6 on 2025-09-18 11:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0041_order_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="restaurant",
        ),
        migrations.AlterField(
            model_name="order",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, verbose_name="Телефон"
            ),
        ),
    ]
