# Generated by Django 5.2.6 on 2025-09-18 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0042_remove_order_restaurant_alter_order_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена на момент заказа",
            ),
            preserve_default=False,
        ),
    ]
