# Generated by Django 5.2.6 on 2025-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_orderedproduct_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Необработан"),
                    ("collect", "Собирается"),
                    ("delivery", "У курьера"),
                    ("done", "Выполнен"),
                    ("cancel", "Отменен"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
