# Generated by Django 5.2.6 on 2025-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_order_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, default=1, verbose_name="Комментарий"),
            preserve_default=False,
        ),
    ]
