# Generated by Django 5.2.6 on 2025-09-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0046_alter_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Принято"),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-15 14:30:45", verbose_name="Время создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Доставлено"
            ),
        ),
    ]
