# Generated by Django 5.2.6 on 2025-09-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0047_order_called_at_order_created_at_order_delivered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Создано"),
        ),
    ]
