# Generated by Django 5.2.6 on 2025-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0050_alter_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[("cash", "Наличными"), ("card", "По карте")],
                db_index=True,
                default="cash",
                max_length=10,
                verbose_name="Оплата",
            ),
        ),
    ]
