# Generated by Django 5.2.6 on 2025-11-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0053_addresspoint_alter_order_restaurant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addresspoint",
            options={
                "verbose_name": "Координаты адреса",
                "verbose_name_plural": "Координаты адресов",
            },
        ),
    ]
