# Generated by Django 5.2.6 on 2025-11-12 11:45

import django.utils.timezone
import foodcartapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0054_alter_addresspoint_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AddressPoint",
        ),
        migrations.AlterField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Принято"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Доставлено"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[("cash", "Наличными"), ("card", "По карте")],
                db_index=True,
                max_length=10,
                verbose_name="Оплата",
            ),
        ),
        migrations.AlterField(
            model_name="orderedproduct",
            name="quantity",
            field=models.IntegerField(
                validators=[foodcartapp.validators.validate_positive],
                verbose_name="Количество",
            ),
        ),
    ]
