# Generated by Django 5.2.6 on 2025-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresspoint",
            name="address",
            field=models.CharField(max_length=500, unique=True, verbose_name="адрес"),
        ),
    ]
